### ISSUE TITLE
Scene is not updated after restart

### ISSUE THREAD

**Issue by Kotolegokot** [Kotolegokot/IrrlichtTest4#1]
If I start the game, then click Escape, Menu, and then Start again, the scene is not updated. Though it works when I choose Fullscreen in Settings.

**Comment by Shirerpeton** [comment]
Now scene is initialising when you start the game and clearing when you quit to the main menu.

**Comment by Kotolegokot** [comment]
a088c56a692bd9cbc2538733fd3a7230f3cc211b
